### ISSUE TITLE
GUI: Recover HD wallet from phrase

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#104]
Semux version: `v1.5.0RC1`

If i provide wrong or empty password, as well as wrong seed to "Recover HD wallet from phrase" the pop-up always says: Success! 1 accounts were imported.

**Comment by honeycrypto** [comment]
Oh, just noticed that it is actually creating a new address in the wallet for every seed/password pair. Is it a desired behaviour? I think it should not create this empty (0 txs) addresses.

**Comment by orogvany** [comment]
For the 'incorrect' password, this is by design from the original spec.  All passwords will generate some result.  It provides more security through plausible deniability.  For wrong seed, looks like I need to bump the version of the hd key lib.  The seed phrase does include a checksum, so at least wrong phrase will throw an error.

I think you are right about on import/restore, if the wallet has any address, and no used acct found, don't add a stub one

**Comment by orogvany** [comment]
Depends on #171

**Comment by semuxgo** [comment]
See #231
