### ISSUE TITLE
Core: Remove the block transaction size limit

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#181]

**Comment by orogvany** [comment]
What do we think for this? 2mb?  We've been running testnet with 8mb, but I think I've been unable to get our testnet validators much past 3mb blocks IIRC.  I think the hardware running testnet nodes may be lower than mainnet.

Since we have a fresh testnet, may be worthwhile running some perf tests again.  Since we last did testing, I know we've made some big changes for native sigs and bulk native sigs, so it may help, but I think network speed was limiting factor

**Comment by semuxgo** [comment]
I was thinking about deprecating the size limit and using the gas model as the only metering mechanism. We're currently assigning a gas cost to the non-vm transactions.

**Comment by orogvany** [comment]
That would be ideal, but we would need to make a few changes to allow for that.

1) validator would need to determine not only what tx's it could propose in size for a given gas cost, but also consider the other 99 deligates speed to reach concensus...  I feel like this will be sizable work.
2) would need the sorting by gas cost in PendingManager
3) Would need to move send/vote/unvote to use gas instead of fee.

Seems like probably a post 1.5 feature?

**Comment by semuxgo** [comment]
For item 3, we don't have to deprecate the usage of gas for send/vote/unvote/delegate. Transaction size of these types are small and bounded. We can charge a fixed gas cost. 

The miner can decide whether to include such a transaction by looking at the "fee / gas_cost".
