### ISSUE TITLE
is there any way to recover wallet.data from mnemonic??

### ISSUE THREAD

**Issue by amazingMan2017** [semuxproject/semux-core#279]
# 🚀 Feature Request

Hi,I am a user of semux,i use the gui wallet in windows.when i want to recovery my lost wallet.data with mnemonic，i found there is no way to recovery wallet from mnemonic, is there some way to recovery my wallet from mnemonic??

**Comment by honeycrypto** [comment]
When you create new wallet, ignore its new mnemonic. Confirm new mnemonic only once to launch the wallet gui. 
Then in top menu go to Wallet -> "Reset HD wallet mnemonic phrase" and use your OLD mnemonic to import & rescan.

**Comment by honeycrypto** [comment]
We have an open issue for adding this feature to the initial screen of wallet creation #261

**Comment by amazingMan2017** [comment]
(1)I first create a wallet, the mnemonic is 
"file pioneer horn reflect catch rice adult final robust lawn gown name"
and get the private key "0x302e020100300506032b657004220420c6e8646958a1d12799ff47c29171235fe7b071d05ed40fa33f63c20c7a616432"

then, i remove the wallet.data。and create a new wallet and then i select in top menu go to Wallet ->"Reset HD wallet mnemonic phrase" and use my OLD mnemonic to reset, but the private key i get is 
"0x302e020100300506032b657004220420abd412874b1bc0b286b22fc6fc976f6061cc5424be6d49ecfee8b42d2c108c97"

how i can restore my OLD private key????

**Comment by honeycrypto** [comment]
@amazingMan2017 first of all don't ever share your private keys and mnemonic phrases in the internet. Even if those public addresses don't have money now, you can forget or send by mistake some coins to those accounts later. 

You can restore from mnemonic only accounts that were derived from it after HD wallets were introduced. Legacy accounts which were created before you generated and saved your _old_ mnemonic cannot be restored from it because they have nothing to do with the new seed and their public/private key pairs existed long before it. 

You need a `wallet.data` to get access to accounts created before Semux 1.5.x (when HD wallets were first enabled in release candidate).

**Comment by orogvany** [comment]
It may be worth adding verbage to remind folks on update that the seed is only for new addresses.  Originally when adding hd key, we did create a new address, but I think that may have been removed and only occurs in manually adding

**Comment by amazingMan2017** [comment]
thanks , i gotted it
